# 跨平台 CLI 工具链：macOS 与 Linux（Homebrew）共用。
# macOS 专属的 tap/cask 在 Brewfile.macos，用 `brew bundle --file=Brewfile.macos` 安装。
tap "anomalyco/tap"
brew "bat"
brew "direnv"
brew "eza"
brew "fd"
brew "fish"
brew "fzf"
brew "mitmproxy"
brew "gh"
brew "git-delta"
brew "iredis"
brew "lazygit"
brew "mise"
brew "mycli"
brew "neovim"
brew "redis", restart_service: :changed
brew "ripgrep"
brew "starship"
brew "sshpass"
brew "stow"
brew "tmux"
brew "yazi"
brew "zoxide"
brew "anomalyco/tap/opencode"
